name: Run tests
on: push

jobs:
  test:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: conda
        uses: matthewrmshin/conda-action@v1

      - name: find the meta dir
        run: |
          conda activate /github/home/myenv
          which python
          echo $CONDA_PREFIX
          echo 'fastai 1.*' >>  /github/home/myenv/conda-meta/pinned
          ls
