name: Run tests
on: push

jobs:
  test:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: conda
        uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: true

      - name: find the meta dir
        run: |
          echo $CONDA_PREFIX
          echo $CONDA
          #ls /home/runner/.conda/envs
          ls
          echo 'fastai 1.*' >>  $CONDA/conda-meta/pinned
