name: Run tests
on: push

jobs:
  test:
    # Containers must run in Linux based operating systems
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: conda
        uses: matthewrmshin/conda-action@v1

      - name: find the meta dir
        run: |
          which python
          echo $CONDA_PREFIX
          echo 'fastai 1.*' >> $CONDA_PREFIX/conda-meta/pinned
          ls
